### ISSUE TITLE
Code consult

### ISSUE THREAD

**Issue by Meansnj** [hoiliu-0801/DNTR#8]
Thank you very much for this outstanding work. I have some questions. After calculating the geometric and semantic losses, do these two losses need to be added to the original total loss? I noticed that in your paper, you conducted comparative experiments by integrating this module into YOLOv8. Could you please guide me on how this was implemented?

**Comment by hoiliu-0801** [comment]
Yes, we add contrastive loss to the total loss during training. For YOLOv8, we implement it using the repo at "https://github.com/ultralytics/ultralytics".

**Comment by Meansnj** [comment]
Thank you for your response. After adding contrastive loss to the training process, did you notice a significant increase in training time? After I added contrastive loss, the training time increased significantly compared to before. Did you experience the same situation in your training? Is this normal? If it's not normal, I will consider whether my code modifications are correct.

**Comment by hoiliu-0801** [comment]
Did you mean the convergence time to reach the same score as the paper? 
In our implementation, we apply a two-step training approach. First, train the standard DetectoRS model (w/o contrastive loss), and then add the contrastive loss and resume training for a few more epochs. Additionally, you can also try to adjust the parameter for contrastive loss since it is sensitive. Sometimes the results are suboptimal if the contrast dominates the total loss.

**Comment by Meansnj** [comment]
Hello, the time I referred to is the time required to train each epoch. After adding the contrastive loss, the time per epoch increased from the original two minutes to thirty minutes. Is this due to the inherent complexity of calculating the contrastive loss, which leads to an increase in training time per epoch? I would like to know if you observed a significant increase in training time per epoch between the first stage without contrastive loss and the second stage with contrastive loss. Thank you.

**Comment by hoiliu-0801** [comment]
I have not noticed this issue before. I'll double-check this and provide an update shortly.

**Comment by Meansnj** [comment]
Thanks

**Comment by hoiliu-0801** [comment]
In our setup with a single 3090 GPU, training one epoch takes 3.27 hours. Without the contrastive loss, the time decreases to around 2.57 hours, primarily due to the multiple for-loop operations in DN-FPN. Thank you for pointing out the training time concerns, we will consider addressing this in the future.
